services:
  db:
    image: postgres:15
    container_name: postgres_si1
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_USER: alumnodb
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: si1
    ports:
      - "9999:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
      - ./actualiza.sql:/docker-entrypoint-initdb.d/2_actualiza.sql
      - ./triggers.sql:/docker-entrypoint-initdb.d/3_triggers.sql
      - ./populate.sql:/docker-entrypoint-initdb.d/4_populate.sql
      - db_data:/var/lib/postgresql/data
  user:
    build:
      context: ./user
      dockerfile: Dockerfile
    container_name: user_service
    ports:
      - "5050:5050"   
    volumes:
      - ./user/user.py:/app/user.py
      - ./user/model.py:/app/model.py
      - ./user/exceptions.py:/app/exceptions.py
    depends_on:
      - db
  movies:
    build:
      context: ./movies
      dockerfile: Dockerfile
    container_name: movies_service
    ports:
      - "5051:5051"
    volumes:
      - ./movies/movies.py:/app/movies.py
      - ./movies/model.py:/app/model.py
      - ./movies/exceptions.py:/app/exceptions.py
    depends_on:
      - db

volumes:
  db_data:

